name: pdf_tools
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/insinfo/pdf_tools
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  ffi: ^2.1.3
  path: ^1.9.1
  shelf: ^1.4.2  
  shelf_router: any
  uuid: any
  mime: any
  http_parser: any

  dart_pdf:
    git:
      url: https://github.com/insinfo/insinfo_dart_pdf
      ref: 31.1.21 # branch name
   
dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
