name: octopus_pdf
description: "A new PDF compress"
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  path: ^1.9.1
  pdf_tools:
    path: ../
  window_manager: ^0.5.1
  flutter_svg: ^2.2.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/logo_octopus.svg
    - assets/logo_octopus_color.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_launcher_icons:  
  # android: true
  # ios: true  
  image_path: "assets/logo_octopus_color.png"
  windows:
    generate: true
    image_path: "assets/logo_octopus_color.png"
    icon_size: 256 
  # macos:
  #   generate: true
  #   image_path: "assets/icon.png"